### ISSUE TITLE
Bug: default slice after identity

### ISSUE THREAD

**Issue by cdgls** [jamievicary/globular#25]
I know you are aware of this, but this is a prominent user-visible bug remaining, so I think it deserves an issue tag.

When clicking identity, the default slice should be set to 1 rather than 0.  Unless you remember this, you often end up building a diagram backwards, and when you remember you have to start over.

(The default slice after undo used to also not work, but I think that has been fixed already.)

**Comment by jamievicary** [comment]
Fixed.
