### ISSUE TITLE
Corrupted workspace encountered

### ISSUE THREAD

**Issue by jamievicary** [jamievicary/globular#36]
A user Ed Morehouse reported to me that he cannot load his workspace: he just gets the message "Preparing to render...". Uncompressing the project data in his JSON file produces a data string which has been truncated, with the final part missing. I have no idea how this could have happened.

**Comment by EdwardMorehouse** [comment]
Just to follow up, I was using Mac OS X 10.11.2 with the Chromium browser (version 50.0).

The project involved constructing cubical sites in a monoidal category and formalizing some results about them (e.g. modular law implies lattice absorption).  I used Unicode in naming some of the cells, in case that's relevant.

**Comment by jamievicary** [comment]
Ah, the unicode is the problem: steps to replicate: load globular.science, change the name of "Cell 1" to "η", Export, then Import.

**Comment by jamievicary** [comment]
I've created https://github.com/jamievicary/globular/issues/37 to represent this bug, and I'm marking this as a duplicate.

**Comment by jamievicary** [comment]
By the way, this sounds cool, please show me when you've got something
formalized!!
