### ISSUE TITLE
Strange bug in braiding

### ISSUE THREAD

**Issue by turion** [jamievicary/globular#45]
Have a look at this workspace: http://globular.science/1607.001
In particular, look at the last morphism I've added, "Cell 11". It was supposed to be the symmetry of the braiding. (I'm trying to formalise the presentation of 4-3-2-bordisms.) I tried several times to add the relation, but always the source or the target would come out wrong. It misses one of the strands. You'll see that Cell 11 doesn't even typecheck, if I understand it correctly.

**Comment by jamievicary** [comment]
Hi, thanks for the report. It works fine for me when I load it up. But I
think I have noticed this sort of behaviour before. The best thing is to
treat this just as a display bug, which it is, and press ahead. I think I
know how to fix it; when I get some time I will post an update.

**Comment by jamievicary** [comment]
Hi Turion, this might be fixed now, can you check it you can still replicate the issue?

**Comment by turion** [comment]
Yes, works now! It already worked on Chromium before, and it now also works on Firefox. Thanks!

**Comment by jamievicary** [comment]
Great.
