### ISSUE TITLE
Hotkeys work in project abstract box

### ISSUE THREAD

**Issue by Cubesoup** [jamievicary/globular#53]
When you click the "project abstract" button at the bottom of the page and begin typing in the box that it creates, the letters that correspond to hotkeys in Globular still work. For example, when one types 'o' in the project abstract box, the letter 'o' appears where it should, but simultaneously the "import" function is invoked, which makes it difficult to type!

**Comment by jamievicary** [comment]
Thanks for the report, now fixed!
