### ISSUE TITLE
Inconsistent labelling/colouring in projections

### ISSUE THREAD

**Issue by akissinger** [jamievicary/globular#72]
Globular seems to use different logic to decide which colour to fill a region in a projection and which tooltip to give. Attached is an example. This cup is the target of a 3-cell (from cup to sock). In the slice view, you can see the 1-cell F is white. So, when switching to the projected view, I would assume I'm looking at this cell from the right side. So, I see coming in the bottom of the diagram: identity on D, then a wire for the 2-cell itself, then F (as the colours indicate). But when I mouse over the white region, it says G (which should be purple in this example).

![globular](https://cloud.githubusercontent.com/assets/881183/17732906/5cdc4444-6474-11e6-8622-5596a077a091.png)
![globular1](https://cloud.githubusercontent.com/assets/881183/17732907/5cdfe59a-6474-11e6-8096-87ed13100228.png)

**Comment by jamievicary** [comment]
Hi Aleks, could you attach a workspace that exhibits this problem?

**Comment by akissinger** [comment]
Sure, attached. In "sock-def", set projection to 1 and mouse over the yellow region. It says F, but it should say G. (Or alternatively, this region should be coloured white).
[colour-problem.json.zip](https://github.com/jamievicary/globular/files/424487/colour-problem.json.zip)

**Comment by jamievicary** [comment]
OK, fixed.
