### ISSUE TITLE
The "project abstract" button disappears

### ISSUE THREAD

**Issue by turion** [jamievicary/globular#76]
I was starting to use the "project abstract" button, mainly to track my todos for the project. When I click on it once, it opens and I can edit the text. When I click it again, it closes completely and the button disappears. I have to reload the workspace in order to find it again. It should stay there.

**Comment by casparwylie** [comment]
Will take a look at this too.

Thanks

**Comment by casparwylie** [comment]
Yes - I have made the changes but don't have access to the server to make
them live. I have pushed the new code to the master repo, so Jamie will
presumably pull it onto the live server soon! Will remind him now.

Cheers
